from __future__ import annotations

from dataclasses import dataclass
import os

from vidrensic.plugins.wfs.codec import FRAGMENT_SIZE
from vidrensic.plugins.wfs.reconstruct import WFSChain, candidate_list, init_chain


@dataclass(frozen=True)
class WFSPathHypothesis:
    """One path-dependent WFS continuation hypothesis for a single start.

    WFS continuation validity depends on the carry/tail produced by the complete
    preceding path. A hypothesis therefore records the full fragment sequence
    instead of pretending continuation edges are context-free.
    """

    start_fragment: int
    fragments: tuple[int, ...]
    total_cost: float
    ambiguous_steps: int
    unresolved_steps: int
    candidate_counts: tuple[int, ...]
    terminal_reason: str

    @property
    def continuations(self) -> int:
        return max(0, len(self.fragments) - 1)

    @property
    def fragment_set(self) -> frozenset[int]:
        return frozenset(self.fragments)


@dataclass(frozen=True)
class WFSGlobalSolution:
    hypotheses: tuple[WFSPathHypothesis, ...]
    total_continuations: int
    total_cost: float
    total_ambiguous_steps: int
    total_unresolved_steps: int
    second_best_continuations: int | None
    second_best_cost: float | None
    alternative_cost_margin: float | None
    combinations_examined: int
    search_truncated: bool
    notes: tuple[str, ...]

    @property
    def has_close_alternative(self) -> bool:
        return self.alternative_cost_margin is not None and self.alternative_cost_margin <= 1.0


@dataclass(frozen=True)
class _BeamState:
    fragments: tuple[int, ...]
    current_fragment: int
    tail: bytes | None
    total_cost: float
    ambiguous_steps: int
    unresolved_steps: int
    candidate_counts: tuple[int, ...]


def _validate_parameters(
    start_fragment: int,
    stop_fragment: int,
    *,
    near: int,
    far: int,
    candidate_top: int,
    beam_width: int,
    max_depth: int,
    max_hypotheses: int,
    data_offset: int,
    fragment_size: int,
) -> None:
    if start_fragment < 0:
        raise ValueError("start_fragment cannot be negative")
    if stop_fragment <= start_fragment:
        raise ValueError("stop_fragment must follow start_fragment")
    if near <= 0 or far < near:
        raise ValueError("require 0 < near <= far")
    if candidate_top <= 0 or candidate_top > 16:
        raise ValueError("candidate_top must be between 1 and 16")
    if beam_width <= 0 or beam_width > 256:
        raise ValueError("beam_width must be between 1 and 256")
    if max_depth <= 0:
        raise ValueError("max_depth must be positive")
    if max_hypotheses <= 0 or max_hypotheses > 4096:
        raise ValueError("max_hypotheses must be between 1 and 4096")
    if data_offset < 0 or fragment_size <= 0:
        raise ValueError("data_offset and fragment_size must be valid")


def _state_sort_key(state: _BeamState) -> tuple:
    # Beam pruning is deterministic. Prefer paths with more proven
    # continuations, then lower distance/structural cost.
    return (-len(state.fragments), state.total_cost, state.fragments)


def _hypothesis_sort_key(item: WFSPathHypothesis) -> tuple:
    return (
        -item.continuations,
        item.unresolved_steps,
        item.ambiguous_steps,
        item.total_cost,
        item.fragments,
    )


def enumerate_path_hypotheses(
    fd: int,
    start_fragment: int,
    stop_fragment: int,
    *,
    near: int = 32,
    far: int = 4096,
    candidate_top: int = 4,
    beam_width: int = 24,
    max_depth: int = 4096,
    max_hypotheses: int = 64,
    data_offset: int = 0,
    fragment_size: int = FRAGMENT_SIZE,
) -> tuple[WFSPathHypothesis, ...]:
    """Enumerate bounded, path-dependent continuation hypotheses for one WFS start.

    Every candidate is structurally probed using the carry/tail generated by
    the exact preceding hypothesis. The beam bounds combinatorial growth while
    retaining competing paths as explicit ambiguity evidence.
    """

    _validate_parameters(
        start_fragment,
        stop_fragment,
        near=near,
        far=far,
        candidate_top=candidate_top,
        beam_width=beam_width,
        max_depth=max_depth,
        max_hypotheses=max_hypotheses,
        data_offset=data_offset,
        fragment_size=fragment_size,
    )

    initial = init_chain(
        fd,
        start_fragment,
        data_offset=data_offset,
        fragment_size=fragment_size,
    )
    if not initial.active:
        reason = "terminal-padding" if initial.tail is None and not initial.unresolved_steps else "invalid-start"
        return (
            WFSPathHypothesis(
                start_fragment=start_fragment,
                fragments=tuple(initial.fragments),
                total_cost=0.0,
                ambiguous_steps=initial.ambiguous_steps,
                unresolved_steps=initial.unresolved_steps,
                candidate_counts=tuple(initial.candidate_counts),
                terminal_reason=reason,
            ),
        )

    active = [
        _BeamState(
            fragments=(start_fragment,),
            current_fragment=start_fragment,
            tail=initial.tail,
            total_cost=0.0,
            ambiguous_steps=initial.ambiguous_steps,
            unresolved_steps=initial.unresolved_steps,
            candidate_counts=(),
        )
    ]
    terminal: list[WFSPathHypothesis] = []

    for _depth in range(max_depth):
        if not active:
            break
        expanded: list[_BeamState] = []

        for state in active:
            compatibility = WFSChain(
                start_fragment=start_fragment,
                current_fragment=state.current_fragment,
                fragments=list(state.fragments),
                tail=state.tail,
                active=True,
                ambiguous_steps=state.ambiguous_steps,
                unresolved_steps=state.unresolved_steps,
                candidate_counts=list(state.candidate_counts),
            )
            options = candidate_list(
                fd,
                compatibility,
                set(state.fragments),
                stop_fragment,
                near=near,
                far=far,
                top=candidate_top,
                data_offset=data_offset,
                fragment_size=fragment_size,
            )
            count = len(options)
            ambiguous = state.ambiguous_steps + (1 if count > 1 else 0)
            counts = state.candidate_counts + (count,)

            if not options:
                terminal.append(
                    WFSPathHypothesis(
                        start_fragment=start_fragment,
                        fragments=state.fragments,
                        total_cost=state.total_cost,
                        ambiguous_steps=ambiguous,
                        unresolved_steps=state.unresolved_steps + 1,
                        candidate_counts=counts,
                        terminal_reason="no-structural-continuation",
                    )
                )
                continue

            for cost, fragment, new_tail in options:
                fragments = state.fragments + (fragment,)
                next_state = _BeamState(
                    fragments=fragments,
                    current_fragment=fragment,
                    tail=new_tail,
                    total_cost=state.total_cost + cost,
                    ambiguous_steps=ambiguous,
                    unresolved_steps=state.unresolved_steps,
                    candidate_counts=counts,
                )
                if new_tail is None:
                    terminal.append(
                        WFSPathHypothesis(
                            start_fragment=start_fragment,
                            fragments=fragments,
                            total_cost=next_state.total_cost,
                            ambiguous_steps=ambiguous,
                            unresolved_steps=state.unresolved_steps,
                            candidate_counts=counts,
                            terminal_reason="terminal-padding",
                        )
                    )
                else:
                    expanded.append(next_state)

        # Deduplicate equivalent fragment paths before beam pruning.
        unique: dict[tuple[int, ...], _BeamState] = {}
        for state in sorted(expanded, key=_state_sort_key):
            unique.setdefault(state.fragments, state)
        active = list(unique.values())[:beam_width]
    else:
        for state in active:
            terminal.append(
                WFSPathHypothesis(
                    start_fragment=start_fragment,
                    fragments=state.fragments,
                    total_cost=state.total_cost,
                    ambiguous_steps=state.ambiguous_steps,
                    unresolved_steps=state.unresolved_steps + 1,
                    candidate_counts=state.candidate_counts,
                    terminal_reason="max-depth",
                )
            )
        active = []

    if active:
        # Defensive path; normal loop exits only when active is empty.
        for state in active:
            terminal.append(
                WFSPathHypothesis(
                    start_fragment=start_fragment,
                    fragments=state.fragments,
                    total_cost=state.total_cost,
                    ambiguous_steps=state.ambiguous_steps,
                    unresolved_steps=state.unresolved_steps + 1,
                    candidate_counts=state.candidate_counts,
                    terminal_reason="search-stopped",
                )
            )

    unique_terminal: dict[tuple[int, ...], WFSPathHypothesis] = {}
    for item in sorted(terminal, key=_hypothesis_sort_key):
        unique_terminal.setdefault(item.fragments, item)
    result = tuple(list(unique_terminal.values())[:max_hypotheses])
    if not result:
        raise RuntimeError("WFS path enumeration produced no hypothesis")
    return result


def _solution_key(items: tuple[WFSPathHypothesis, ...]) -> tuple:
    return (
        -sum(item.continuations for item in items),
        sum(item.unresolved_steps for item in items),
        sum(item.ambiguous_steps for item in items),
        sum(item.total_cost for item in items),
        tuple(item.fragments for item in items),
    )


def select_global_hypotheses(
    hypotheses_by_start: dict[int, tuple[WFSPathHypothesis, ...]],
    *,
    max_combinations: int = 250_000,
) -> WFSGlobalSolution:
    """Choose globally compatible WFS paths without reusing physical fragments.

    The objective is forensic and lexicographic: maximize the number of
    structurally proven continuations first, then minimize unresolved/ambiguous
    evidence and finally physical-distance cost. The second-best compatible
    solution is retained as ambiguity evidence.
    """

    if not hypotheses_by_start:
        raise ValueError("at least one start hypothesis set is required")
    if max_combinations <= 0:
        raise ValueError("max_combinations must be positive")

    starts = tuple(sorted(hypotheses_by_start))
    for start in starts:
        options = hypotheses_by_start[start]
        if not options:
            raise ValueError(f"start {start} has no hypotheses")
        if any(item.start_fragment != start for item in options):
            raise ValueError(f"hypothesis start mismatch for {start}")

    # Explore the most constrained starts first, while preserving final output
    # order by physical start fragment.
    exploration = tuple(sorted(starts, key=lambda start: (len(hypotheses_by_start[start]), start)))
    ordered_options = {
        start: tuple(sorted(hypotheses_by_start[start], key=_hypothesis_sort_key))
        for start in starts
    }

    examined = 0
    truncated = False
    best: tuple[WFSPathHypothesis, ...] | None = None
    second: tuple[WFSPathHypothesis, ...] | None = None
    best_key: tuple | None = None
    second_key: tuple | None = None

    selected: dict[int, WFSPathHypothesis] = {}

    def consider() -> None:
        nonlocal examined, best, second, best_key, second_key
        examined += 1
        items = tuple(selected[start] for start in starts)
        key = _solution_key(items)
        if best_key is None or key < best_key:
            if best is not None and items != best:
                second, second_key = best, best_key
            best, best_key = items, key
        elif items != best and (second_key is None or key < second_key):
            second, second_key = items, key

    def walk(position: int, used: frozenset[int]) -> None:
        nonlocal truncated
        if truncated:
            return
        if position == len(exploration):
            if examined >= max_combinations:
                truncated = True
                return
            consider()
            return

        start = exploration[position]
        for option in ordered_options[start]:
            if option.fragment_set & used:
                continue
            selected[start] = option
            walk(position + 1, used | option.fragment_set)
            selected.pop(start, None)
            if truncated:
                return

    walk(0, frozenset())
    if best is None:
        raise RuntimeError("no globally disjoint WFS path combination exists")

    total_continuations = sum(item.continuations for item in best)
    total_cost = sum(item.total_cost for item in best)
    second_continuations = None if second is None else sum(item.continuations for item in second)
    second_cost = None if second is None else sum(item.total_cost for item in second)
    margin = None
    if second is not None and second_continuations == total_continuations:
        margin = max(0.0, second_cost - total_cost)

    return WFSGlobalSolution(
        hypotheses=best,
        total_continuations=total_continuations,
        total_cost=total_cost,
        total_ambiguous_steps=sum(item.ambiguous_steps for item in best),
        total_unresolved_steps=sum(item.unresolved_steps for item in best),
        second_best_continuations=second_continuations,
        second_best_cost=second_cost,
        alternative_cost_margin=margin,
        combinations_examined=examined,
        search_truncated=truncated,
        notes=(
            "WFS continuation hypotheses preserve path-dependent carry/tail state",
            "selected paths are globally disjoint in physical fragment space",
            "objective maximizes proven continuation count before minimizing uncertainty and distance cost",
            "a truncated global search is REVIEW evidence and must not be presented as an optimum",
        ),
    )


def build_global_chains(
    fd: int,
    starts: list[int] | tuple[int, ...],
    stop_fragment: int,
    *,
    near: int = 32,
    far: int = 4096,
    candidate_top: int = 4,
    beam_width: int = 24,
    max_depth: int = 4096,
    max_hypotheses: int = 64,
    max_combinations: int = 250_000,
    data_offset: int = 0,
    fragment_size: int = FRAGMENT_SIZE,
) -> tuple[list[WFSChain], WFSGlobalSolution]:
    """Enumerate path-dependent WFS hypotheses and solve all starts jointly."""

    if not starts:
        return [], WFSGlobalSolution((), 0, 0.0, 0, 0, None, None, None, 0, False, ())
    if len(set(starts)) != len(starts):
        raise ValueError("duplicate start fragments are invalid")
    if stop_fragment <= max(starts):
        raise ValueError("stop_fragment must follow all start fragments")

    hypotheses = {
        start: enumerate_path_hypotheses(
            fd,
            start,
            stop_fragment,
            near=near,
            far=far,
            candidate_top=candidate_top,
            beam_width=beam_width,
            max_depth=max_depth,
            max_hypotheses=max_hypotheses,
            data_offset=data_offset,
            fragment_size=fragment_size,
        )
        for start in sorted(starts)
    }
    solution = select_global_hypotheses(hypotheses, max_combinations=max_combinations)

    chains: list[WFSChain] = []
    for item in solution.hypotheses:
        chains.append(
            WFSChain(
                start_fragment=item.start_fragment,
                current_fragment=item.fragments[-1],
                fragments=list(item.fragments),
                tail=None,
                active=False,
                ambiguous_steps=item.ambiguous_steps,
                unresolved_steps=item.unresolved_steps,
                candidate_counts=list(item.candidate_counts),
            )
        )
    return chains, solution


def open_and_build_global_chains(
    source: os.PathLike[str] | str,
    starts: list[int] | tuple[int, ...],
    stop_fragment: int,
    **kwargs,
) -> tuple[list[WFSChain], WFSGlobalSolution]:
    """Convenience wrapper used by validation tooling and tests."""

    fd = os.open(source, os.O_RDONLY)
    try:
        return build_global_chains(fd, starts, stop_fragment, **kwargs)
    finally:
        os.close(fd)
